AUTHOR := hmartzol
NAME := ../checker
MAIN := main.c
CFLAGS := -Wall -Wextra -Werror -g3 -fsanitize=address
PINC := ../libft/inc libftx2/inc inc
CLIB := ../libft libftx2
LIB := ../libft/libft.a libftx2/libftx2.a
LLARGS := libftx2/minilibx_X11/mlx.a -lXext -lX11
MLARGS := libftx2/minilibx_macos_sierra/libmlx.a -framework OpenGL -framework AppKit
include ../Makefiles/Makefile.gen
