AUTHOR := hmartzol
NAME := ../checker
MAIN := main.c
CFLAGS := -Wall -Wextra -Werror -g3 -fsanitize=address
PINC := ../libft/inc libftx2/inc inc
CLIB := ../libft libftx2
LIB := ../libft/libft.a libftx2/libftx2.a
include ../Makefiles/Makefile.gen
