AUTHOR := hmartzol
NAME   := libftx2.a
CFLAGS := -Wall -Wextra -Werror -g -Wno-deprecated -Wno-deprecated-declarations
PINC   := ../../libft/inc inc
LPINC  := minilibx_X11
MPINC  := minilibx_macos
CLIB   := ../../libft
LCLIB  := minilibx_X11
MCLIB  := minilibx_macos
LIB    := ../../libft/libft.a
LLIB   := minilibx_X11/libmlx.a
MLIB   := minilibx_macos/libmlx.a
LLARGS := -lXext -lX11
MLARGS := -framework OpenGL -framework AppKit
include ../../Makefiles/Makefile.gen
