AUTHOR := hmartzol
NAME   := libftx2.a
CFLAGS := -Wall -Wextra -Werror -g -Wno-deprecated -Wno-deprecated-declarations
PINC   := ../../libft/inc inc
LPINC  := minilibx_X11
MPINC  := minilibx_macos_sierra
CLIB   := ../../libft
include ../../Makefiles/Makefile.gen
